"""pcSecPichia probe prototype migrated into the pcsec_pichia package.

This submodule wraps the original ``local_runs/pichia_hlf_opn_probe/pichia_hlf_opn_probe.py``
prototype so it can be imported as ``pcsec_pichia.probe``. The prototype is the
parameterized OPN/hLF secretion pipeline and is kept intact (zero numeric change)
during the package migration. Later phases will replace its internal loaders with
the existing ``pcsec_pichia`` adapters and align its output against MATLAB LP
baselines.

The prototype code lives in :mod:`pcsec_pichia.probe._prototype` and is re-exported
here for convenience. Path helpers ``repo_root`` and ``output_dir`` were adjusted
for the new file location: ``repo_root`` returns the repository root, ``output_dir``
still points at ``local_runs/pichia_hlf_opn_probe`` so generated artifacts remain
comparable to the original prototype outputs.
"""

from pcsec_pichia.probe._prototype import (  # noqa: F401  re-export public API
    AA_MW,
    AA_PATTERN,
    AminoAcidStoichiometry,
    CombinedEnzymeData,
    CobraModel,
    DEFAULT_TRADEOFF_MUS,
    IMPROVEMENT_REL_TOLERANCE,
    MetabolicEnzymeData,
    RULE_TOKEN_PATTERN,
    SecretoryComplexEntry,
    SecretoryEnzymeData,
    SolveResult,
    TargetModelBuildResult,
    TargetProteinEnzymeData,
    TargetSpec,
    accumulate,
    add_misfolding_plan,
    append_rows,
    best_delta,
    build_candidate_table,
    build_pcsec_constraint_matrices,
    build_supported_target_model,
    build_target_enzymedata,
    candidate_sort_key,
    candidate_table_row,
    classify_candidate_effect,
    classify_secretory_process,
    clean_sequence,
    coat_other_stoichiometries,
    collect_compartment_reactions,
    default_ko_genes,
    default_oe_reactions,
    dsb_stoichiometries,
    evaluate_coefficient_ref,
    evaluate_rule_after_ko,
    formal_status,
    format_candidate_rows,
    format_number,
    format_tradeoff_rows,
    golgi_n_stoichiometries,
    golgi_o_stoichiometries,
    inactive_reactions_for_gene,
    infer_gene_symbols_from_reaction,
    is_opn_like_supported_target,
    is_soluble_secretory_supported_target,
    load_aa_stoichiometry,
    load_combined_enzymedata,
    load_hlf_default,
    load_metabolic_enzymedata,
    load_opn_default,
    load_pcsec_pichia_model,
    load_secretory_enzymedata,
    load_single_struct,
    load_targets,
    longest_common_suffix,
    main,
    matlab_round_positive,
    mature_stoichiometries,
    metabolic_coupling_rows,
    misfolding_constraint_rows,
    mitochondrial_rows,
    modeled_protein_fraction,
    ng_stoichiometries,
    nonempty_string_items,
    numeric_items,
    numeric_vector,
    og_stoichiometries,
    opn_like_er_golgi_transport_stoichiometries,
    opn_like_og_misfolding_stoichiometries,
    opn_like_target_stoichiometries,
    opn_like_translocation_stoichiometries,
    output_dir,
    parse_mu_points,
    prepare_glucose_model,
    proteasome_rows,
    protein_mass_rows,
    relative_change,
    repo_root,
    ribosome_assembly_rows,
    ribosome_translation_rows,
    run_ko_screen,
    run_oe_screen,
    run_pcsec_growth_tradeoff,
    run_pcsec_ko_screen,
    run_pcsec_oe_screen,
    run_pcsec_reaction_ko_screen,
    secretory_complex_subunit_map,
    secretory_coupling_rows,
    set_media_pp_like_matlab,
    soluble_misfolding_stoichiometries,
    soluble_secretory_target_stoichiometries,
    solve_maximize,
    solve_pcsec_maximize,
    sparse_row,
    string_list,
    string_scalar,
    target_features,
    target_from_mapping,
    target_reaction_plan,
    target_secretion_smoke,
    transport_to_secretory_stoichiometries,
    write_outputs,
)

__all__ = [name for name in dir() if not name.startswith("_")]
